import Config

# Configure your database
config :deep_thought, DeepThought.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "deep_thought_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :deep_thought, DeepThoughtWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "2kRj9u4TH3xUqXW5BORBLHegdfi3u46HVMM3f8Y48MQndcNIHu8dhR8aKT0rC/bq",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :deep_thought, DeepThoughtWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/deep_thought_web/(live|views)/.*(ex)$",
      ~r"lib/deep_thought_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Secret variables
deepl_auth_key =
  System.get_env("DEEPL_AUTH_KEY") ||
    raise "environment variable DEEPL_AUTH_KEY is missing."

config :deep_thought, :deepl, auth_key: deepl_auth_key

slack_bot_token =
  System.get_env("SLACK_BOT_TOKEN") ||
    raise "environment variable SLACK_BOT_TOKEN is missing."

slack_signing_secret =
  System.get_env("SLACK_SIGNING_SECRET") ||
    raise "environment variable SLACK_SIGNING_SECRET is missing."

slack_feedback_channel = System.get_env("SLACK_FEEDBACK_CHANNEL")

config :deep_thought, :slack,
  bot_token: slack_bot_token,
  feedback_channel: slack_feedback_channel,
  signing_secret: slack_signing_secret
