defmodule DeepThought.Slack.Language do
  @moduledoc """
  Module that allows for converstion between country codes (used by Slack flag emojis) and language codes (used by DeepL
  translation engine).
  """

  @type t() :: %__MODULE__{slack_code: String.t(), deepl_code: String.t()}
  defstruct slack_code: "", deepl_code: ""

  alias DeepThought.Slack.Language

  @doc """
  Given a country code as a `String`, attempt conversion to a language code.
  """
  @spec new(String.t()) :: {:ok, Language.t()} | {:error, :unknown_language}
  def new("flag-" <> reaction), do: do_new(reaction)
  def new(reaction), do: do_new(reaction)

  @spec do_new(String.t()) :: {:ok, Language.t()} | {:error, :unknown_language}
  defp do_new(reaction) do
    case Map.get(mapping(), reaction) do
      nil -> {:error, :unknown_language}
      value -> {:ok, %Language{slack_code: reaction, deepl_code: String.upcase(value)}}
    end
  end

  @spec mapping() :: %{String.t() => String.t()}
  defp mapping,
    do: %{
      "bg" => "bg",
      "cz" => "cs",
      "dk" => "da",
      "at" => "de",
      "de" => "de",
      "ch" => "de",
      "li" => "de",
      "gr" => "el",
      "gb" => "en-gb",
      "ac" => "en-us",
      "ag" => "en-us",
      "ai" => "en-us",
      "as" => "en-us",
      "au" => "en-us",
      "bb" => "en-us",
      "bn" => "en-us",
      "bs" => "en-us",
      "bw" => "en-us",
      "bz" => "en-us",
      "ca" => "en-us",
      "ck" => "en-us",
      "cx" => "en-us",
      "dm" => "en-us",
      "fj" => "en-us",
      "fk" => "en-us",
      "fm" => "en-us",
      "gd" => "en-us",
      "gg" => "en-us",
      "gh" => "en-us",
      "gi" => "en-us",
      "gm" => "en-us",
      "gs" => "en-us",
      "gu" => "en-us",
      "gy" => "en-us",
      "im" => "en-us",
      "io" => "en-us",
      "je" => "en-us",
      "jm" => "en-us",
      "ke" => "en-us",
      "ki" => "en-us",
      "kn" => "en-us",
      "ky" => "en-us",
      "lc" => "en-us",
      "lr" => "en-us",
      "mp" => "en-us",
      "ms" => "en-us",
      "mu" => "en-us",
      "mw" => "en-us",
      "na" => "en-us",
      "nf" => "en-us",
      "ng" => "en-us",
      "nz" => "en-us",
      "pn" => "en-us",
      "pw" => "en-us",
      "sb" => "en-us",
      "sc" => "en-us",
      "sg" => "en-us",
      "sh" => "en-us",
      "sl" => "en-us",
      "ss" => "en-us",
      "ta" => "en-us",
      "tc" => "en-us",
      "tt" => "en-us",
      "ug" => "en-us",
      "um" => "en-us",
      "us" => "en-us",
      "vc" => "en-us",
      "vg" => "en-us",
      "vi" => "en-us",
      "zm" => "en-us",
      "zw" => "en-us",
      "ar" => "es",
      "bo" => "es",
      "cl" => "es",
      "co" => "es",
      "cr" => "es",
      "cu" => "es",
      "do" => "es",
      "ea" => "es",
      "ec" => "es",
      "es" => "es",
      "gq" => "es",
      "gt" => "es",
      "hn" => "es",
      "ic" => "es",
      "mx" => "es",
      "ni" => "es",
      "pa" => "es",
      "pe" => "es",
      "pr" => "es",
      "py" => "es",
      "sv" => "es",
      "uy" => "es",
      "ve" => "es",
      "ee" => "et",
      "fi" => "fi",
      "bf" => "fr",
      "bi" => "fr",
      "bj" => "fr",
      "bl" => "fr",
      "cd" => "fr",
      "cf" => "fr",
      "cg" => "fr",
      "ci" => "fr",
      "cm" => "fr",
      "cp" => "fr",
      "dj" => "fr",
      "fr" => "fr",
      "ga" => "fr",
      "gf" => "fr",
      "gn" => "fr",
      "gp" => "fr",
      "mc" => "fr",
      "ml" => "fr",
      "mq" => "fr",
      "nc" => "fr",
      "ne" => "fr",
      "pf" => "fr",
      "pm" => "fr",
      "re" => "fr",
      "sn" => "fr",
      "td" => "fr",
      "tf" => "fr",
      "tg" => "fr",
      "wf" => "fr",
      "yt" => "fr",
      "hu" => "hu",
      "it" => "it",
      "sm" => "it",
      "va" => "it",
      "jp" => "ja",
      "lt" => "lt",
      "lv" => "lv",
      "aw" => "nl",
      "be" => "nl",
      "bq" => "nl",
      "cw" => "nl",
      "nl" => "nl",
      "sr" => "nl",
      "sx" => "nl",
      "pl" => "pl",
      "ao" => "pt-br",
      "br" => "pt-br",
      "cv" => "pt-br",
      "gw" => "pt-br",
      "mz" => "pt-br",
      "st" => "pt-br",
      "pt" => "pt-pt",
      "ro" => "ro",
      "ru" => "ru",
      "sk" => "sk",
      "si" => "sl",
      "se" => "sv",
      "cn" => "zh"
    }
end
